### ISSUE TITLE
openapi-compiler should take a output directory path.

### ISSUE THREAD

**Issue by guptasu** [googleapis/openapi-compiler#16]
Currently the output files are dropped inside the current working directory of the process. Ability to pass the output directory or output file path will be handy especially when calling this tool from another application through process.start (out of proc).

**Comment by guptasu** [comment]
Do you mind if I take this issue, unless you have already started working on it ?

**Comment by timburks** [comment]
Please do, that's good.

**Comment by timburks** [comment]
Resolved in [this commit](https://github.com/googleapis/openapi-compiler/commit/953976002db322e89f5fc3c38bd0cc681fc54199)
