### ISSUE TITLE
null output when trying to load the following sample swagger specs

### ISSUE THREAD

**Issue by guptasu** [googleapis/openapi-compiler#17]
Test files live inside directory:

https://github.com/googleapis/api-compiler/tree/master/src/test/java/com/google/api/tools/framework/importers/swagger/testdata

library_example_yaml.yaml
additional_properties.json
top_level_security_ext.json
x_google_allow_extension_all.json
x_google_allow_extension_all_with_existing_catchall_methods.json

@timburks May be the change you are making currently to make some real world swagger files work, would automatically fix this problem.

**Comment by timburks** [comment]
These specs all load following [this commit](https://github.com/googleapis/openapi-compiler/commit/acf83074d0f7748f6af4980925dc43f19e4d208c). The problem was that the generator was missing support for pattern properties at the top level.

**Comment by guptasu** [comment]
Cool. thanks
